### ISSUE TITLE
.show() can not resolve

### ISSUE THREAD

**Issue by Sekhtech** [coreORB/SelectionDialogs#1]
When i pass an Activity Context as a parameter of .show(), i.e build().show(A.this), it gives me an error. so can u plz tell me how I can i use this library for the activity?

**Comment by coreORB** [comment]
You should use it this way:

```
new ColorSelectDialog.Builder(getContext())
.setColors(ColorPalettes.loadMaterialDesignColors500(getContext(), false))
.build().show(getFragmentManager(), TAG_SELECT_COLOR_DIALOG);
```

Take a look at [example](https://github.com/coreORB/SelectionDialogs/blob/master/sample/src/main/java/pl/coreorb/selectiondialogssample/MainActivityFragment.java), it's fragment, but usage in activity follows same pattern.

**Comment by Sekhtech** [comment]
Thank you for your quick reply. now when i use this ".build().show(getFragmentManager(), TAG_SELECT_ICON_DIALOG);" it is showing me that "cannot resolve method'show(android.app.FragmentManager),java.lang.String'".

**Comment by Sekhtech** [comment]
OK i solve it by using getSupportFragmentManager but the icons are not colored. why?

**Comment by coreORB** [comment]
I've tested it on Android 4.4 and 5.1 and everything was ok. Which version are you using?

**Comment by Sekhtech** [comment]
android 5.1.. and it is solved.. thank you..
